### ISSUE TITLE
Python 2.7 from Pyenv can't import collections under wracker

### ISSUE THREAD

**Issue by dan-passaro** [dan-passaro/wracker#2]
Reproduce like so:

```
$ for file in $(ls -A); do echo ---$file---; cat $file; done
---.python-version---
2.7.12
---requirements.in---
---requirements.txt---
$ readlink -f $(which python)
~/.pyenv/shims/python
$ python --version
Python 2.7.12
$ wracker exec python -c 'import collections'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/collections.py", line 20, in <module>
    from _collections import deque, defaultdict
ImportError: No module named _collections
```

Completely unclear to me what is causing this or what a solution might be. Although `wracker -p ~/.pyenv/versions/2.7.12/bin/python` exec python -c 'import collections'` works fine

**Comment by dan-passaro** [comment]
This also doesn't cause a problem if called in this cumbersome way:

    wracker -p ~/.wracker/envs/python-2.7.12/bin/python exec ~/.wracker/envs/python-2.7.12/bin/python -c 'import collections'

What might be a good idea is to put the Wracker virtualenv bin path in front. (If not that then a proxy Python command that also sets important env vars.)
